//
//  Constants.h
//  PandaKeyboard
//
//  Created by yanzhao on 2017/5/23.
//  Copyright © 2017年 姚宗超. All rights reserved.
//

#import <Foundation/Foundation.h>


 #define STRING_SPACE @" "

UIKIT_EXTERN int const CODE_ENTER;
UIKIT_EXTERN int const CODE_TAB;
UIKIT_EXTERN int const CODE_SPACE;
UIKIT_EXTERN int const CODE_PERIOD;
UIKIT_EXTERN int const CODE_COMMA;
UIKIT_EXTERN int const CODE_DASH;
UIKIT_EXTERN int const CODE_SINGLE_QUOTE;
UIKIT_EXTERN int const CODE_DOUBLE_QUOTE;
UIKIT_EXTERN int const CODE_SLASH;
UIKIT_EXTERN int const CODE_BACKSLASH;
UIKIT_EXTERN int const CODE_VERTICAL_BAR;
UIKIT_EXTERN int const CODE_COMMERCIAL_AT;
UIKIT_EXTERN int const CODE_PLUS;
UIKIT_EXTERN int const CODE_PERCENT;
UIKIT_EXTERN int const CODE_CLOSING_PARENTHESIS;
UIKIT_EXTERN int const CODE_CLOSING_SQUARE_BRACKET;
UIKIT_EXTERN int const CODE_CLOSING_CURLY_BRACKET;
UIKIT_EXTERN int const CODE_CLOSING_ANGLE_BRACKET;
UIKIT_EXTERN int const CODE_INVERTED_QUESTION_MARK; // ¿
UIKIT_EXTERN int const CODE_INVERTED_EXCLAMATION_MARK; // ¡
UIKIT_EXTERN int const CODE_GRAVE_ACCENT;
UIKIT_EXTERN int const CODE_CIRCUMFLEX_ACCENT;
UIKIT_EXTERN int const CODE_TILDE;
UIKIT_EXTERN int const CODE_QUESSTION;
UIKIT_EXTERN int const CODE_EXCLAMATION;
UIKIT_EXTERN int const CODE_COLON;
UIKIT_EXTERN int const CODE_SEMICOLON;


UIKIT_EXTERN int const CODE_SHIFT;
UIKIT_EXTERN int const CODE_SWITCH_ALPHA_SYMBOL;
UIKIT_EXTERN int const CODE_DELETE;
UIKIT_EXTERN int const CODE_EMOJI;
UIKIT_EXTERN int const CODE_SHIFT_ENTER;

UIKIT_EXTERN int const CODE_LANGUAGE_SWITCH;

@interface Constants : NSObject

@end
